Repository Fantasy-Fit/fantasy-fit-web, pull requests merged in 2023-05, with the labels that each got.

#83 added authenticate to post controller and refetched after CRUD
  api/app/controllers/posts_controller.rb
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/Record.jsx
Labels: enhancement

#82 increase height of banner--fadeBottom
  client/src/components/Main.css
Labels: styling

#84 render dates to competition page
  api/app/models/workout.rb
  api/app/serializers/competition_serializer.rb
  api/db/seeds.rb
  client/src/pages/account/MainFeed.css
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/tournaments/TournamentPage.jsx
Labels: bug, enhancement

#86 Added delete option to the workouts created within last 2 days
  api/app/controllers/workouts_controller.rb
  api/app/serializers/workout_serializer.rb
  api/config/routes.rb
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/tournaments/TournamentPage.jsx
  client/src/store/game/workoutApiSlice.js
  client/src/store/game/workoutSlice.js
Labels: functionality

#104 fix workout numbers in sidebar
  client/src/app/store.js
  client/src/pages/account/Profile.jsx
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/account/Sidebar.jsx
  client/src/store/game/competitionSlice.js
Labels: bug

#105 Add creator to new comp by default v2
  client/src/pages/account/Sidebar.jsx
  client/src/pages/newcompetition/CreateCompetition.jsx
Labels: bug, enhancement

#108 Fixed leaderBoard update after deleting workout
  api/app/controllers/workouts_controller.rb
  client/src/pages/account/RecentWorkouts.jsx
Labels: bug

#109 New workout posted user changed to bot
  api/app/controllers/workouts_controller.rb
  client/src/pages/account/RecentWorkouts.jsx
Labels: bug

#117 build friendships - request, ignore, accept, delete
  api/app/controllers/friendships_controller.rb
  api/app/controllers/users_controller.rb
  api/app/models/friendship.rb
  api/app/models/user.rb
  api/config/routes.rb
  client/src/pages/friend/FriendsPage.jsx
  client/src/pages/friend/PendingFriendCard.jsx
  client/src/pages/friend/SearchFriendResult.jsx
  client/src/store/auth/authApiSlice.js
  client/src/store/social/friendApiSlice.js
Labels: enhancement, functionality

#118 style header
  client/src/components/Header.css
  client/src/components/Header.jsx
  client/src/components/HeaderOption.css
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/account/Sidebar.jsx
Labels: styling

#119 added validation to removing friends
  api/app/models/friendship.rb
Labels: enhancement

#120 Styling
  client/src/App.css
  client/src/components/Header.jsx
  client/src/pages/account/CompetitionCard.css
  client/src/pages/account/CompetitionCard.jsx
  client/src/pages/account/EditProfileModal.jsx
  client/src/pages/account/MainFeed.css
  client/src/pages/account/MainFeed.jsx
  client/src/pages/account/Profile.jsx
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/account/Sidebar.jsx
  client/src/pages/friend/FriendCard.css
  client/src/pages/friend/FriendCard.jsx
  client/src/pages/friend/FriendsPage.css
  client/src/pages/friend/FriendsPage.jsx
  client/src/pages/newcompetition/JoinCompetitionModal.jsx
  client/src/pages/tournaments/CompetitionPage.css
  client/src/pages/tournaments/Leaderboard.jsx
  client/src/pages/tournaments/PostCard.css
  client/src/pages/tournaments/PostCard.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/store/game/leaderboardApiSlice.js
Labels: styling

#121 configure endpoints in apiSlices for deployment
  client/src/app/api/apiSlice.js
  client/src/store/auth/authApiSlice.js
  client/src/store/game/participantsApiSlice.js
  client/src/store/game/workoutApiSlice.js
Labels: functionality

#122 add redirect file for Netlify deployment
  client/public/_redirects
Labels: enhancement

#123 use Rack-CORS and clean up for backend deployment
  api/Gemfile
  api/Gemfile.lock
  api/app/controllers/application_controller.rb
  api/app/controllers/friendships_controller.rb
  api/app/controllers/users_controller.rb
  api/config/initializers/cors.rb
  api/config/routes.rb
  client/public/4959925.png
  client/public/6679633.png
  client/src/app/api/apiSlice.js
Labels: enhancement, deployment

#126 started mobile styling
  client/src/components/Header.css
  client/src/index.css
  client/src/pages/account/CompetitionCard.css
  client/src/pages/account/InputOption.css
  client/src/pages/account/MainFeed.css
  client/src/pages/account/Profile.css
  client/src/pages/account/Sidebar.css
  client/src/pages/tournaments/CompetitionPage.css
Labels: styling

#127 Style profile page
  client/src/pages/account/CompetitionCard.css
  client/src/pages/account/MainFeed.css
Labels: styling

#129 tidy up unused features, fix re-rendering on friends page
  api/config/initializers/cors.rb
  api/config/routes.rb
  client/src/components/Header.jsx
  client/src/pages/account/CompetitionCard.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/account/Sidebar.jsx
  client/src/pages/friend/FriendCard.css
  client/src/pages/friend/FriendCard.jsx
  client/src/pages/friend/FriendsPage.css
  client/src/pages/friend/FriendsPage.jsx
  client/src/pages/friend/PendingFriendCard.jsx
  client/src/pages/friend/SearchFriendResult.jsx
  client/src/pages/newcompetition/Join.css
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/JoinCompetitionModal.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/store/social/friendApiSlice.js
  client/src/store/social/friendSlice.js
Labels: bug, styling, functionality, deployment

#131 continue styling for mobile responsiveness
  api/config/initializers/cors.rb
  client/src/components/Header.css
  client/src/pages/account/CompetitionCard.css
  client/src/pages/account/CompetitionCard.jsx
  client/src/pages/account/MainFeed.css
  client/src/pages/account/Profile.css
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/friend/FriendCard.jsx
  client/src/pages/friend/PendingFriendCard.jsx
  client/src/pages/friend/SearchFriendResult.jsx
  client/src/pages/newcompetition/Join.css
  client/src/pages/newcompetition/NewCompetition.css
  client/src/pages/tournaments/CompetitionPage.css
  client/src/pages/tournaments/PostCard.css
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/Record.jsx
Labels: styling

#135 styled join.css
  client/src/components/Layout.jsx
  client/src/pages/newcompetition/Join.css
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/JoinCompetitionModal.jsx
  client/src/pages/newcompetition/NewCompetition.css
Labels: styling

#143 Sockets
  api/app/channels/notifications_channel.rb
  api/app/controllers/posts_controller.rb
  api/app/controllers/workouts_controller.rb
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/app/store.js
  client/src/components/Header.jsx
  client/src/pages/notifications/Notifications.jsx
  client/src/store/notifications/notificationsSlice.js
Labels: enhancement, functionality

#148 chat feature created
  api/app/channels/messages_channel.rb
  api/app/controllers/messages_controller.rb
  api/app/models/message.rb
  api/app/models/user.rb
  api/app/serializers/message_serializer.rb
  api/config/routes.rb
  api/db/migrate/20230526164606_create_messages.rb
  api/db/migrate/20230526190022_add_user_referece_to_message.rb
  api/db/schema.rb
  client/package-lock.json
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/pages/chat/Messages.css
  client/src/pages/chat/Messages.jsx
Labels: enhancement

#147 Fix auth redirect on jwt expiry
  api/app/controllers/application_controller.rb
  api/app/controllers/authentication_controller.rb
  api/app/controllers/competitions_controller.rb
  api/app/models/blacklisted_token.rb
  api/config/routes.rb
  api/config/schedule.rb
  api/lib/json_web_token.rb
  api/lib/tasks/blacklisted_tokens.rake
  client/src/App.jsx
  client/src/app/api/apiSlice.js
  client/src/app/api/reauthApiSlice.js
  client/src/components/Header.jsx
  client/src/components/PageNotFound.jsx
  client/src/pages/account/Profile.jsx
  client/src/pages/auth/Authorization.jsx
  client/src/pages/auth/Login.jsx
  client/src/pages/auth/RequireAuth.jsx
  client/src/store/auth/authApiSlice.js
  client/src/store/auth/userSlice.js
Labels: bug, enhancement, functionality, authentication

#153 config ws URL in production.rb
  api/config/environments/production.rb
  client/src/pages/chat/Messages.jsx
Labels: deployment

#154 changed fetching messages to test chat
  client/src/pages/chat/Messages.jsx
Labels: bug

#156 Netlify preview cors error
  api/config/initializers/cors.rb
Labels: bug, deployment, authentication

#158 Tidy Ups Changes to Client
  client/index.html
  client/public/fantasyfit-logo.png
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/public/robots.txt
  client/src/pages/account/CompetitionCard.jsx
  client/src/pages/chat/Messages.jsx
  client/src/pages/tournaments/Record.jsx
  client/src/pages/tournaments/TournamentPage.jsx
Labels: bug, styling
