Repository Fantasy-Fit/fantasy-fit-web, pull requests merged in 2023-04, with the labels that each got.

#38 small bug fix with unpermitted params
  api/app/controllers/workouts_controller.rb
  client/src/pages/tournaments/Leaderboard.jsx
  client/src/pages/tournaments/Record.jsx
Labels: bug

#41 style main profile page
  api/app/serializers/competition_serializer.rb
  api/db/migrate/20230411183656_add_icon_tocompetitions.rb
  api/db/schema.rb
  client/public/4959925.png
  client/public/6679633.png
  client/src/data/fitnessIcons.js
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/newcompetition/Create.jsx
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/NewCompetition.css
Labels: enhancement, styling

#42 add additional fields to sign up form
  api/app/controllers/authentication_controller.rb
  api/app/controllers/users_controller.rb
  api/app/models/user.rb
  api/config/routes.rb
  client/src/pages/account/EditProfileModal.jsx
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/auth/Login.css
  client/src/pages/auth/Login.jsx
  client/src/pages/auth/Signup.css
  client/src/pages/auth/Signup.jsx
  client/src/pages/newcompetition/NewCompetition.jsx
  client/src/store/auth/authApiSlice.js
  client/src/store/auth/userSlice.js
Labels: bug, enhancement, styling

#49 Added migrations for text in posts and comments
  api/app/models/competition.rb
  api/app/serializers/post_serializer.rb
  api/config/routes.rb
  api/db/migrate/20230413142007_add_text_column_post.rb
  api/db/migrate/20230413142157_add_text_column_comments.rb
  api/db/schema.rb
  api/db/seeds.rb
Labels: enhancement

#48 added join method in competitions controller
  api/app/controllers/competitions_controller.rb
  api/config/routes.rb
Labels: enhancement

#50 style competition page
  client/src/pages/tournaments/CompetitionPage.css
  client/src/pages/tournaments/Feed.jsx
  client/src/pages/tournaments/Leaderboard.jsx
  client/src/pages/tournaments/Record.jsx
  client/src/pages/tournaments/TournamentPage.jsx
Labels: styling

#51 Posts fetched and rendered to the Competition page
  api/app/controllers/competitions_controller.rb
  api/app/controllers/posts_controller.rb
  api/app/models/competition.rb
  client/src/app/store.js
  client/src/pages/account/Profile.jsx
  client/src/pages/tournaments/Feed.jsx
  client/src/pages/tournaments/PostCard.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/TournamentPage.jsx
  client/src/store/game/competitionApiSlice.js
  client/src/store/game/feedApiSlice.js
  client/src/store/game/feedSlice.js
  docker-compose.yml
Labels: enhancement

#52 created Add Post to the Feed
  api/app/controllers/posts_controller.rb
  client/src/pages/tournaments/Feed.jsx
  client/src/pages/tournaments/PostCard.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/TournamentPage.jsx
  client/src/store/game/feedSlice.js
Labels: enhancement

#53 creating workout also creates a post
  api/app/controllers/workouts_controller.rb
  client/src/pages/tournaments/CompetitionPage.css
  client/src/pages/tournaments/Feed.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/Record.jsx
  client/src/pages/tournaments/TournamentPage.jsx
  docker-compose.yml
Labels: enhancement

#60 Build join a competition
  api/app/controllers/competitions_controller.rb
  api/config/routes.rb
  client/src/App.jsx
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/JoinCompetition.jsx
  client/src/store/game/competitionApiSlice.js
  client/src/store/game/competitionSlice.js
Labels: enhancement, functionality

#61 added Profile icons, Header, and Sidebar
  client/package-lock.json
  client/package.json
  client/src/components/Header.css
  client/src/components/Header.jsx
  client/src/components/HeaderOption.css
  client/src/components/HeaderOption.jsx
  client/src/components/Main.jsx
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/account/Sidebar.jsx
Labels: styling

#62 wrap curr competition icons and fix width
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
Labels: styling

#64 fix close modal bug issue #57
  client/src/pages/account/EditProfileModal.jsx
  client/src/pages/account/Profile.jsx
Labels: bug

#67 Add dates to create competition
  api/db/migrate/20230424150554_add_dates_to_competition.rb
  api/db/schema.rb
  client/src/pages/newcompetition/CreateCompetition.jsx
Labels: bug, enhancement

#68 Fixed logout and Navbar fix
  client/src/App.jsx
  client/src/components/Header.css
  client/src/components/Header.jsx
  client/src/components/Layout.jsx
  client/src/pages/account/Profile.jsx
  client/src/pages/auth/Authorization.jsx
  client/src/pages/auth/RequireAuth.jsx
  client/src/pages/tournaments/TournamentPage.jsx
Labels: bug

#69 Add start and end date validations
  client/src/pages/newcompetition/CreateCompetition.jsx
Labels: bug

#75 Merging changes from style-header-sidebar
  api/app/controllers/competitions_controller.rb
  api/config/routes.rb
  client/src/App.jsx
  client/src/components/Header.css
  client/src/components/Header.jsx
  client/src/components/HeaderOption.jsx
  client/src/index.css
  client/src/pages/account/InputOption.css
  client/src/pages/account/InputOption.jsx
  client/src/pages/account/MainFeed.css
  client/src/pages/account/MainFeed.jsx
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/account/Sidebar.css
  client/src/pages/account/Sidebar.jsx
  client/src/pages/newcompetition/CreateCompetition.jsx
  client/src/pages/newcompetition/Join.css
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/JoinCompetition.jsx
  client/src/pages/newcompetition/JoinCompetitionModal.jsx
  client/src/store/game/competitionApiSlice.js
Labels: bug, enhancement, styling

#72 Build join modal
  api/app/controllers/competitions_controller.rb
  api/config/routes.rb
  client/src/App.jsx
  client/src/pages/account/Profile.css
  client/src/pages/account/Profile.jsx
  client/src/pages/newcompetition/Join.css
  client/src/pages/newcompetition/Join.jsx
  client/src/pages/newcompetition/JoinCompetition.jsx
  client/src/pages/newcompetition/JoinCompetitionModal.jsx
  client/src/store/game/competitionApiSlice.js
Labels: bug, enhancement, styling

#77 creating a new competition will redirect to profile page
  api/app/controllers/workouts_controller.rb
  client/src/pages/account/Profile.jsx
  client/src/pages/account/RecentWorkouts.jsx
  client/src/pages/account/Sidebar.jsx
  client/src/pages/auth/Login.jsx
  client/src/pages/newcompetition/CreateCompetition.jsx
  client/src/pages/tournaments/Posts.jsx
  client/src/pages/tournaments/TournamentPage.jsx
  client/src/store/auth/userSlice.js
  client/src/store/game/competitionSlice.js
  client/src/store/game/workoutApiSlice.js
  client/src/store/game/workoutSlice.js
Labels: bug, enhancement
